Organizations:

    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: ../crypto-config/ordererOrganizations/trueclaim.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"
    - &AllParticipants
        Name: AllParticipants
        ID: AllParticipantsMSP
        MSPDir: ../crypto-config/peerOrganizations/allparticipants.trueclaim.com/msp
        AnchorPeers:
            - Host: peer1.allparticipants.trueclaim.com
              Port: 7051
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('AllParticipantsMSP.admin', 'AllParticipantsMSP.peer', 'AllParticipantsMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('AllParticipantsMSP.admin', 'AllParticipantsMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('AllParticipantsMSP.admin')"

#Capabilities

Capabilities:
    Channel: &ChannelCapabilities
        V1_4_3: true
        V1_3: false
        V1_1: false
    Orderer: &OrdererCapabilities
        V1_4_2: true
        V1_1: false
    Application: &ApplicationCapabilities
        V1_4_2: true
        V1_3: false
        V1_2: false
        V1_1: false

#Application

Application: &ApplicationDefaults
    Organizations:
    Policies: &ApplicationDefaultPolicies
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "ANY Admins"
    Capabilities: *ApplicationCapabilities

Orderer: &OrdererDefaults

    OrdererType: solo
    
    Addresses:
        - orderer.trueclaim.com:7050
    
    BatchTimeout: 2s
    
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    
    Capabilities: *OrdererCapabilities
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "ANY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults
    Policies:
        # Who may invoke the 'Deliver' API
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        # Who may invoke the 'Broadcast' API
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        # By default, who may modify elements at this config level
        Admins:
            Type: ImplicitMeta
            Rule: "ANY Admins"
    Capabilities:
        <<: *ChannelCapabilities

Profiles:
  
    OrdererGenesis:
        <<: *ChannelDefaults
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            ClaimsConsortium:
                Organizations:
                    - *AllParticipants

    ChannelGenesis:
        Consortium: ClaimsConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *AllParticipants
            Capabilities:
                <<: *ApplicationCapabilities