version: '2'

services:

  # Setting up certificate authority for AllParticipants Org
  ca.allparticipants.trueclaim.com:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.allparticipants.trueclaim.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.allparticipants.trueclaim.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/4f994cc17b14cc0d590fe01deff0dc1d5def31c720ad118b6cb56399faf334bc_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.allparticipants.trueclaim.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/4f994cc17b14cc0d590fe01deff0dc1d5def31c720ad118b6cb56399faf334bc_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/allparticipants.trueclaim.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.allparticipants.trueclaim.com
    networks:
      - claimsnetwork