version: '2'

services:

  peer0.allparticipants.trueclaim.com:
    container_name: peer0.allparticipants.trueclaim.com
    extends:
      file: basic_peer_configuration.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.allparticipants.trueclaim.com
      - CORE_PEER_ADDRESS=peer0.allparticipants.trueclaim.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.allparticipants.trueclaim.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.allparticipants.trueclaim.com:7051
      - CORE_PEER_LOCALMSPID=AllParticipantsMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/allparticipants.trueclaim.com/peers/peer0.allparticipants.trueclaim.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/allparticipants.trueclaim.com/peers/peer0.allparticipants.trueclaim.com/tls:/etc/hyperledger/fabric/tls
        - peer0.allparticipants.trueclaim.com:/var/hyperledger/production
        - ./crypo-config/ordererOrganizations:/etc/hyperledger/fabric/orderer_tls_cert
    ports:
      - 7051:7051
      - 7053:7053

  peer1.allparticipants.trueclaim.com:
    container_name: peer1.allparticipants.trueclaim.com
    extends:
      file: basic_peer_configuration.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.allparticipants.trueclaim.com
      - CORE_PEER_ADDRESS=peer1.allparticipants.trueclaim.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.allparticipants.trueclaim.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.allparticipants.trueclaim.com:7051
      - CORE_PEER_LOCALMSPID=AllParticipantsMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/allparticipants.trueclaim.com/peers/peer1.allparticipants.trueclaim.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/allparticipants.trueclaim.com/peers/peer1.allparticipants.trueclaim.com/tls:/etc/hyperledger/fabric/tls
        - peer1.allparticipants.trueclaim.com:/var/hyperledger/production
        - ./crypo-config/ordererOrganizations:/etc/hyperledger/fabric/orderer_tls_cert
    ports:
      - 8051:7051
      - 8053:7053
